src/Entity/Activite.php
<?php

namespace App\Entity;

use App\Repository\ActiviteRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ActiviteRepository::class)
 */
class Activite
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $dateActivite;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $titre;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $contenu;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $noteActivite;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Departement;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ville;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateActivite(): ?\DateTimeInterface
    {
        return $this->dateActivite;
    }

    public function setDateActivite(?\DateTimeInterface $dateActivite): self
    {
        $this->dateActivite = $dateActivite;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(?string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(?string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getNoteActivite(): ?int
    {
        return $this->noteActivite;
    }

    public function setNoteActivite(?int $noteActivite): self
    {
        $this->noteActivite = $noteActivite;

        return $this;
    }

    public function getDepartement(): ?string
    {
        return $this->Departement;
    }

    public function setDepartement(?string $Departement): self
    {
        $this->Departement = $Departement;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Repository\ArticleRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="home")
     * @IsGranted("ROLE_USER")
     * @param ArticleRepository $repo
     * @return Response
     */
    public function index(ArticleRepository $repo)
    {

        return $this->render('home/index-blog.html.twig', [
            //Résultat trié par date descandante
            'articles' => $repo->findBy([], ['date' => 'DESC']),

        ]);
    }
}

templates/home/index-blog.html.twig
{% extends 'base.html.twig' %}

{% block title %}Carnet de voyage{% endblock %}

{% block body %}
    <section id="banner-img" class="banner-img bg-banner-img">

        <div class="row no-gutters">
            <div class="col-12 col-md-5"></div>
            <div class="col-12 col-md-7">
                <div class="overlay"></div>
                <div class="row no-gutters height1">
                    <div class="col-2 d-flex justify-content-center align-items-center">
                        <p class="verticle-text text-white padding-vert">Nos séjours, nos vacances, nos
                            découvertes...</p>
                    </div>
                    <div class="col-10 d-flex  align-items-center">
                        <h1 class="main-heading text-white">CARNET<br>DE<br>VOYAGES</h1>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="about" class="about">
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-6">
                    <div class="about-text text-left d-flex">
                        <p class="verticle-text text-grey pt-2">A propos de nous...</p>
                        <h1 class="main-heading ml-3">Nos avis, nos découvertes, nos virées...</h1>
                    </div>
                </div>
                <div class="col-12 col-md-6">
                    <p class="sub-heading text-grey text-justify">Nous aimons découvrir de nouveaux endroits et ce blog est le reflet
                        de nos expériences ou nous partageons nos virées
                        le temps d'un week end, nos vacances, nos séjours.
                        <br><br>
                        Il y aura des avis sur les campings ou nous sommes passés, les lieux, monuments et activités qui
                        nous ont plus ou déplus. L'idée principale de ce blog est
                        de rassembler nos souvenirs au même endroit et accessible partout ou nous disposons d'une
                        connexion internet.
                    </p>
                </div>
            </div>
        </div>
    </section>
    {% if app.user %}
        <section id="portfolio" class="portfolio">
            <div class="container">
                <div id="js-grid-masonry-projects" class="cbp cbp-l-grid-masonry-projects">

                    {% for article in articles %}
                        <!--Articles-->
                        <div class="cbp-item">
                            <div class="cbp-caption">
                                <div class="cbp-caption-defaultWrap">
                                    {% for image in article.images | slice(0,1) %}
                                        <img src="{{ asset('/uploads/' ~ image.image) }} " alt="Image de présentation"
                                             style="width: 350px">
                                    {% endfor %}
                                </div>

                                <div class="cbp-caption-activeWrap">
                                    <div class="cbp-l-caption-alignCenter">
                                        <div class="cbp-l-caption-body">
                                            <a href="{{ path('article_show', {'id': article.id}) }}"
                                               class="btn blog-btn cbp-l-caption-buttonLeft">LIRE
                                                L'ARTICLE</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="portfolio-text">
                                <p class="portfolio-vert text-grey">{{ article.departement }}</p>
                                <a class="text-black" href="{{ path('article_show', {'id': article.id}) }}">
                                    <h2 class="heading ml-3">
                                        {{ article.ville }} <a href="{{ path('article_edit', {'id': article.id}) }}"> <i
                                                    class="fas fa-pen"></i> </a><br>
                                        {% if article.noteCamping == 1 %}
                                            <i class="las la-star rating-star"></i>
                                        {% elseif article.noteCamping == 2 %}
                                            <i class="las la-star rating-star"></i>
                                            <i class="las la-star rating-star"></i>
                                        {% elseif article.noteCamping == 3 %}
                                            <i class="las la-star rating-star"></i>
                                            <i class="las la-star rating-star"></i>
                                            <i class="las la-star rating-star"></i>
                                        {% elseif article.noteCamping == 4 %}
                                            <i class="las la-star rating-star"></i>
                                            <i class="las la-star rating-star"></i>
                                            <i class="las la-star rating-star"></i>
                                            <i class="las la-star rating-star"></i>
                                        {% elseif article.noteCamping == 5 %}
                                            <i class="las la-star rating-star"></i>
                                            <i class="las la-star rating-star"></i>
                                            <i class="las la-star rating-star"></i>
                                            <i class="las la-star rating-star"></i>
                                            <i class="las la-star rating-star"></i>
                                        {% endif %}
                                    </h2>

                                </a>
                                <p class="date text-grey">{{ article.date | date('d/m/Y') }}</p>
                                <div class="horizontal-line"></div>
                                <p class="sub-heading text-grey mt-3 text-justify">{{ article.intro }}
                            </div>
                        </div>

                    {% endfor %}

                    <!-- Fin de l'article -->

                </div>
            </div>
        </section>
    {% endif %}

{% endblock %}